// Auto-generated by generate_galleries.py — do not edit manually.
// Re-run the script after adding or removing artwork.
const GALLERIES = new Set([
  "64437300001",
  "64437300002",
  "644637008086",
  "644637132545",
  "644637139612",
  "644637253028",
  "644637310660",
  "644637420352",
  "644637439095",
  "644637454708"
]);
